# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170908_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='defusemessage',
            name='viewed_by_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
