# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_defusemessage_viewed_by_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='defusemessage',
            name='star_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defusemessage',
            name='star_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
