# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170909_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defusemessage',
            name='star_by_receiver',
        ),
        migrations.RemoveField(
            model_name='defusemessage',
            name='star_by_sender',
        ),
    ]
