# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='defusemessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='profiles.DefuseMessage'),
        ),
    ]
