# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 01:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import quests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('explosion_datetime', models.DateTimeField(default=datetime.datetime(2017, 9, 8, 1, 49, 48, 249840, tzinfo=utc))),
                ('reward_type', models.CharField(choices=[('MonetaryH', 'Monetary (Hourly)'), ('MonetaryF', 'Monetary (Flat)'), ('Non-monetary', 'Non-monetary'), ('Voluntary', 'Voluntary')], default='MonetaryH', max_length=15)),
                ('mon_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('non_mon_rewards', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_images', models.ImageField(upload_to=quests.models.get_image_path)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='quests.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_thumbnail', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_thumbnail', models.ImageField(blank=True, null=True, upload_to=quests.models.get_profile_thumbnail_path)),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL),
        ),
    ]
