# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 00:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import quests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('explosion_datetime', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 0, 46, 58, 733321, tzinfo=utc))),
                ('reward_type', models.CharField(choices=[('Monetary', 'Monetary'), ('Non-monetary', 'Non-monetary')], default='Monetary', max_length=15)),
                ('mon_reward_rate', models.CharField(choices=[('Hourly', 'Hourly'), ('Flat', 'Flat')], default='Monetary', max_length=10)),
                ('mon_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('non_mon_rewards', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=quests.models.get_image_path)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='quests.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(null=True, upload_to=quests.models.get_profile_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL),
        ),
    ]
