# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileimage',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 2, 15, 46, 844945, tzinfo=utc)),
        ),
    ]
