# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 1, 41, 15, 817864, tzinfo=utc)),
        ),
    ]
