# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20170906_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 20, 12, 6, 454566, tzinfo=utc)),
        ),
    ]
