# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20170808_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 22, 58, 12, 523324, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='mon_reward_rate',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Flat', 'Flat')], default='Monetary', max_length=10),
        ),
    ]
