# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20170721_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='objectives',
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(),
        ),
    ]
