# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_auto_20170809_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 23, 1, 23, 159565, tzinfo=utc)),
        ),
    ]
