# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_auto_20170722_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
