# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_auto_20170809_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 10, 23, 46, 55, 508071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quest',
            name='mon_reward_rate',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Flat', 'Flat')], default='Hourly', max_length=10, null=True),
        ),
    ]
