# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_auto_20170722_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL),
        ),
    ]
