# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_auto_20170722_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
