# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0007_auto_20170909_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='explosion_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 12, 3, 36, 34, 93161, tzinfo=utc)),
        ),
    ]
