# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_auto_20170723_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
