# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0011_remove_quest_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='mon_reward',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='nonmon_rewards',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quest',
            name='reward_type',
            field=models.CharField(choices=[('Monetary', 'Monetary'), ('Non-monetary', 'Non-monetary')], default='Monetary', max_length=15),
        ),
    ]
