# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0012_auto_20170724_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='nonmon_rewards',
            new_name='rewards',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='mon_reward',
        ),
    ]
