# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import quests.models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0013_auto_20170725_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=quests.models.get_image_path)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='quests.Quest')),
            ],
        ),
    ]
