# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import quests.models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0015_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=quests.models.get_profile_image_path),
        ),
    ]
