# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0017_auto_20170802_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('Ticking', 'Ticking'), ('Diffused', 'Diffused'), ('Exploded', 'Exploded')], default='Ticking', max_length=15),
        ),
    ]
