# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0020_auto_20170803_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='status',
        ),
    ]
