# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0021_remove_quest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='rewards',
        ),
        migrations.AddField(
            model_name='quest',
            name='mon_reward',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='mon_reward_rate',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Flat', 'Flat')], default='Monetary', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='non_mon_rewards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
