# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0022_auto_20170806_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='mon_reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
